ANN MODULE

**Data Preprocessing**

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [33]:
dataset= pd.read_csv('Churn_Modelling.csv')
x= dataset.iloc[:,3:-1].values #input attribute
y= dataset.iloc[:,-1].values # output attribute

**encode categorical**

In [34]:
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()
x[:,2]= label_encoder.fit_transform(x[:,2])# gender

In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [48]:
x[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0,shuffle=True)

In [38]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

**Build ANN**

In [39]:
from pandas.io.formats.style_render import Sequence
ann= tf.keras.models.Sequential()

In [40]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [41]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [42]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

**Train ANN**

In [43]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
ann.fit(x_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5889 - accuracy: 0.7642
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4765 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4512 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4378 - accuracy: 0.8030
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4287 - accuracy: 0.8127
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4223 - accuracy: 0.8171
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4122 - accuracy: 0.8217
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4074 - accuracy: 0.8231
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4030 - accura

In [50]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 24ms/step
[[False]]


In [51]:
y_prediction=ann.predict(x_test)
y_prediction=(y_prediction>0.5)
print(np.concatenate((y_prediction.reshape(len(y_prediction),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
c_matrix=confusion_matrix(y_test,y_prediction)
print(c_matrix)
accuracy_score(y_test,y_prediction)

[[1513   82]
 [ 201  204]]


0.8585